/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.newtonpaiva.gc.ui.aluno;

import br.newtonpaiva.gc.ui.contrato.TelaContrato;
import br.newtonpaiva.gc.ui.utils.MensagemUtil;
import br.newtonpaiva.modelo.Aluno;
import br.newtonpaiva.modelo.Curso;
import br.newtonpaiva.modelo.excessoes.AlunoInvalidoException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.ResourceBundle;
/**
 *
 * @author Adriano
 */
public class TelaAluno extends javax.swing.JDialog {

    private Aluno alunoEdicao;

    /**
     * Creates new form TelaAluno
     *
     * @param parent
     * @param modal
     */
    public TelaAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        /*
        * posiciona a tela no centro da tela
         */
        setLocationRelativeTo(parent);
        /*
        * ao usuário clicar enter ele aciona o botão Salvar
         */
        getRootPane().setDefaultButton(btnSalvar);
        /*
        * Inicia o componente de cursos
         */
        CursosComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        imgLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblRa = new javax.swing.JLabel();
        edtRa = new javax.swing.JTextField();
        lblNomeAluno = new javax.swing.JLabel();
        edtNomeAluno = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        edtCpf = new javax.swing.JFormattedTextField();
        lblEmail = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        lblDeficiente = new javax.swing.JLabel();
        cbbDeficiente = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblCurso = new javax.swing.JLabel();
        cbbCurso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setResizable(false);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Aluno"));

        lblRa.setText("RA");

        lblNomeAluno.setText("Nome do aluno");

        lblCpf.setText("CPF");

        try {
            edtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblEmail.setText("Email");

        lblDeficiente.setText("Deficiente");

        cbbDeficiente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Selecione...>>", "N", "S" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeficiente)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRa)
                            .addComponent(lblCpf)
                            .addComponent(edtRa)
                            .addComponent(cbbDeficiente, 0, 187, Short.MAX_VALUE)
                            .addComponent(edtCpf))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeAluno)
                            .addComponent(lblEmail))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRa)
                    .addComponent(lblNomeAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtRa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDeficiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbDeficiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Curso"));

        lblCurso.setText("Curso");

        cbbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Selecione...>>", "SISTEMAS DE INFORMACAO", "ENGENHARIA QUIMICA", "ENGENHARIA DE PRODUÇÃO", "ENGENHARIA DE CONTROLE E AUTOMAÇÃO", "ENGENHARIA ELETRICA", "ENGENHARIA AMBIENTAL", "ARQUITETURA E URBANISMO", "ENGENHARIA MECANICA", "ENGENHARIA CIVIL", "MEDICINA VETERINARIA", "ENFERMAGEM", "PSICOLOGIA", "FARMACIA", "FISIOTERAPIA", "ODONTOLOGIA", "CIENCIAS BIOLOGICAS", "ESTETICA E COSMETICA", "RELACOES PUBLICAS", "PUBLICIDADE E PROPAGANDA", "JORNALISMO", "CIENCIAS CONTABEIS", "ADMINISTRACAO", "DIREITO" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurso)
                    .addComponent(cbbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(btnSalvar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgLogo))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        /*
        * Limpa os componentes
         */
        Limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private final ResourceBundle bundle = ResourceBundle.getBundle("MessageBundle");
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        String Inserir = "N";
        //Se o curso edição é nulo
        if (alunoEdicao == null) {
            //Inicia uma nova classe
            alunoEdicao = new Aluno();
            Inserir = "S";
        }
        //Alterar o campo deficiente
        String deficiente = "";
        if (cbbDeficiente.getSelectedIndex() == 1) {
            deficiente = Aluno.NAO_DEFICIENTE;
        } else if (cbbDeficiente.getSelectedIndex() == 2) {
            deficiente = Aluno.DEFICIENTE;
        }
        //Inicia uma nova classe de curso
        Curso c = new Curso();
        try {
            if (cbbCurso.getSelectedIndex() > 0) {

                List<Curso> lista = Curso.buscarPorNome((String) cbbCurso.getSelectedItem());
                if (lista.size() < 1) {
                    MensagemUtil.exibirDialogo("curso.nao.existe");
                    return;
                }
                lista.forEach(Cursos -> {
                    c.setId(Cursos.getId());
                });
            } else {
                MensagemUtil.exibirDialogo("curso.nao.existe");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaAluno.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        //Seta o nome do aluno para salvar (Inserir ou editar)
        alunoEdicao.setNome(edtNomeAluno.getText());
        alunoEdicao.setCpf(edtCpf.getText());
        alunoEdicao.setCurso(c);
        alunoEdicao.setDeficiente(deficiente);
        alunoEdicao.setEmail(edtEmail.getText());
        alunoEdicao.setRa(edtRa.getText());
        try {
            //Salvar
            alunoEdicao.salvar();
            //Mensagem de acordo com a açãso (Edição ou inserção)
            if (Inserir.equals("S")) {
                MensagemUtil.exibirDialogo("aluno.ok.inserir");
                Limpar();
                alunoEdicao = null;
            } else {
                MensagemUtil.exibirDialogo("aluno.ok.alterar");
            }
        } catch (AlunoInvalidoException ex) {
            cbbCurso.requestFocus();
            Logger.getLogger(TelaAluno.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (SQLException ex) {
            Logger.getLogger(TelaAluno.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaAluno dialog = new TelaAluno(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbbCurso;
    private javax.swing.JComboBox<String> cbbDeficiente;
    private javax.swing.JFormattedTextField edtCpf;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNomeAluno;
    private javax.swing.JTextField edtRa;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDeficiente;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNomeAluno;
    private javax.swing.JLabel lblRa;
    // End of variables declaration//GEN-END:variables

    public void exibirDados(Aluno a) {
        //Iguala a classe que veio a variavel global
        alunoEdicao = a;
        //seta os valores aos campos
        edtCpf.setText(a.getCpf());
        edtEmail.setText(a.getEmail());
        edtNomeAluno.setText(a.getNome());
        edtRa.setText(a.getRa());
        if (a.getDeficiente().equals("S")) {
            cbbDeficiente.setSelectedItem(Aluno.DEFICIENTE);
        } else {
            cbbDeficiente.setSelectedItem(Aluno.NAO_DEFICIENTE);
        }
        cbbCurso.setSelectedItem(a.getCurso().getCurso());
        btnLimpar.setEnabled(false);
    }

    private void Limpar() {
        //Limpa os campos
        edtCpf.setText("");
        edtEmail.setText("");
        edtNomeAluno.setText("");
        edtRa.setText("");
        cbbCurso.setSelectedIndex(0);
        cbbDeficiente.setSelectedIndex(0);
    }

    private void CursosComponente() {
        try {
            List<Curso> lista = Curso.buscarTodos();
            // Limpa o componente
            cbbCurso.removeAllItems();
            cbbCurso.addItem("<<Selecione um item>>");
            lista.forEach(emp -> {
                cbbCurso.addItem(emp.getCurso());
            });
        } catch (SQLException ex) {
            Logger.getLogger(TelaContrato.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
}
