/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.newtonpaiva.gc.ui.empresa;

import br.newtonpaiva.gc.ui.contrato.TelaContrato;
import br.newtonpaiva.gc.ui.utils.TelaPesquisa;
import br.newtonpaiva.modelo.Empresa;
import br.newtonpaiva.modelo.excessoes.EmpresaInvalidaException;
import br.newtonpaiva.util.CpfCnpjUtil;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 11321114
 */
public class TelaEmpresa extends javax.swing.JDialog {

    /**
     * Creates new form TelaEmpresa
     */
    private Empresa empresa;
    private Empresa empresaSelecionada;

    public TelaEmpresa(JFrame aThis, boolean b) {
        super(aThis, b);

        initComponents();
        ImageIcon imagemTituloJanela = new ImageIcon(getClass().getResource("/LogoPequena.jpg"));
        setIconImage(imagemTituloJanela.getImage());
        setLocationRelativeTo(null);
        txtNomeEmpresa.setText("");

        this.setResizable(false);
        empresa = new Empresa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        lblCNPJEm = new javax.swing.JLabel();
        txtCNPJEmpresa = new javax.swing.JTextField();
        lblResponsavelEmpresa = new javax.swing.JLabel();
        txtResponsavelEmpresa = new javax.swing.JTextField();
        lblEnderecoEm = new javax.swing.JLabel();
        txtEnderecoEmpresa = new javax.swing.JTextField();
        lblBairroEm = new javax.swing.JLabel();
        txtBairroEmpresa = new javax.swing.JTextField();
        lblCidadeEm = new javax.swing.JLabel();
        txtCidadeEmpresa = new javax.swing.JTextField();
        lblUFEm = new javax.swing.JLabel();
        txtUFEmpresa = new javax.swing.JTextField();
        lblTelEm = new javax.swing.JLabel();
        txtTelEmpresa = new javax.swing.JTextField();
        lblEmailEm = new javax.swing.JLabel();
        txtEmailEmpresa = new javax.swing.JTextField();
        lblObservacoesEm = new javax.swing.JLabel();
        txtObservacoesEmpresa = new javax.swing.JTextField();
        btnLimparEmpresa = new javax.swing.JButton();
        btnSalvarEmpresa = new javax.swing.JButton();
        btnConsultarEmpresa = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Empresa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblNome.setText("Nome");

        lblCNPJEm.setText("CNPJ");

        lblResponsavelEmpresa.setText("Responsável");

        lblEnderecoEm.setText("Endereço");

        lblBairroEm.setText("Bairro");

        lblCidadeEm.setText("Cidade");

        lblUFEm.setText("UF");

        lblTelEm.setText("Tel");

        lblEmailEm.setText("Email");

        lblObservacoesEm.setText("Observações");

        btnLimparEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        btnLimparEmpresa.setText("Limpar");
        btnLimparEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparEmpresaActionPerformed(evt);
            }
        });

        btnSalvarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        btnSalvarEmpresa.setText("Salvar");
        btnSalvarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEmpresaActionPerformed(evt);
            }
        });

        btnConsultarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lookup.png"))); // NOI18N
        btnConsultarEmpresa.setText("Consultar");
        btnConsultarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEmpresaActionPerformed(evt);
            }
        });

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/del.png"))); // NOI18N
        jToggleButton1.setText("Excluir");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(txtNomeEmpresa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCNPJEm)
                            .addComponent(txtCNPJEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(184, 184, 184))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnderecoEm)
                            .addComponent(txtEnderecoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBairroEm)
                            .addComponent(txtBairroEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCidadeEm)
                            .addComponent(txtCidadeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUFEm)
                            .addComponent(txtUFEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtObservacoesEmpresa)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtResponsavelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblResponsavelEmpresa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTelEm)
                                .addGap(150, 150, 150)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblEmailEm)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtEmailEmpresa))
                                .addGap(20, 20, 20))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnLimparEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvarEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultarEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblObservacoesEm)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(lblCNPJEm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCNPJEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnderecoEm)
                            .addComponent(lblBairroEm)
                            .addComponent(lblCidadeEm)
                            .addComponent(lblUFEm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEnderecoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBairroEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCidadeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUFEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblResponsavelEmpresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtResponsavelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblTelEm)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEmailEm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(lblObservacoesEm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObservacoesEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparEmpresa)
                    .addComponent(btnSalvarEmpresa)
                    .addComponent(btnConsultarEmpresa)
                    .addComponent(jToggleButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparEmpresaActionPerformed
        txtNomeEmpresa.setText("");
        txtCNPJEmpresa.setText("");
        txtEnderecoEmpresa.setText("");
        txtBairroEmpresa.setText("");
        txtCidadeEmpresa.setText("");
        txtUFEmpresa.setText("");
        txtResponsavelEmpresa.setText("");
        txtTelEmpresa.setText("");
        txtEmailEmpresa.setText("");
        txtObservacoesEmpresa.setText("");
        Empresa empresa;

    }//GEN-LAST:event_btnLimparEmpresaActionPerformed

    private void btnSalvarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEmpresaActionPerformed
        /* if (txtRA.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione o aluno");
            txtRA.requestFocus();
        } else if (txtCNPJEmpresa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione a empresa");
            txtCNPJEmpresa.requestFocus();
        }else if (txtDataEntrada.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a data de entrada");
            txtDataEntrada.requestFocus();
        }else if (txtDataInicio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a data de início");
            txtDataInicio.requestFocus();
        }else if (txtDataTermino.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a data de término");
            txtDataTermino.requestFocus();
        }else if (cbxTipoContrato.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione o tipo de contrato");
            cbxTipoContrato.requestFocus();
        }else if (Integer.parseInt(txtCHDiaria.getValue().toString()) <= 0) {
            JOptionPane.showMessageDialog(null, "Informe a carga horária diária");
            txtCHDiaria.requestFocus();
        }else if (Integer.parseInt(txtCHSemanal.getValue().toString()) <= 0) {
            JOptionPane.showMessageDialog(null, "Informe a carga horária semanal");
            txtCHSemanal.requestFocus();
        } */

        try {
            empresa.setNome(txtNomeEmpresa.getText());
            empresa.setBairro(txtBairroEmpresa.getText());
            empresa.setCnpj(txtCNPJEmpresa.getText());
            empresa.setEndereco(txtEnderecoEmpresa.getText());
            empresa.setCidade(txtCidadeEmpresa.getText());
            empresa.setUf(txtUFEmpresa.getText());
            empresa.setResponsavel(txtResponsavelEmpresa.getText());
            empresa.setTelefone(txtTelEmpresa.getText());
            empresa.setEmail(txtEmailEmpresa.getText());
            empresa.setObs(txtObservacoesEmpresa.getText());

            empresa.salvar();
            JOptionPane.showMessageDialog(null, "Informações salvas com sucesso!");
        } catch (EmpresaInvalidaException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(TelaEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar empresa no banco de dados");
            Logger.getLogger(TelaEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSalvarEmpresaActionPerformed

    private void btnConsultarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEmpresaActionPerformed
        TelaPesquisa tela = new TelaPesquisa(
                (JFrame) this.getParent(), true);
        tela.setTitle("Pesquisa de Empresa");
        tela.getCbxTipoFiltro().removeAllItems();
        tela.getCbxTipoFiltro().addItem("Id");
        tela.getCbxTipoFiltro().addItem("Razão Social");
        tela.getCbxTipoFiltro().addItem("CNPJ");

        tela.getTableModel().addColumn("ID");
        tela.getTableModel().addColumn("CNPJ");
        tela.getTableModel().addColumn("Razão Social");

        tela.getBtnConsultar().addActionListener(
                new AcaoPesquisaEmpresa(tela.getTxtFiltro(), tela.getCbxTipoFiltro(), tela.getTableModel()));

        tela.getBtnSelecionar().addActionListener(
                new AcaoSelecionarEmpresa(tela.getTblResultadoPesquisa(), tela));

        tela.setVisible(true);
    }//GEN-LAST:event_btnConsultarEmpresaActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        if (empresaSelecionada.getId() == null) {
            JOptionPane.showMessageDialog(null, "Nenhum registro selecionado");
        } else {
            int i = JOptionPane.showConfirmDialog(null, "Confirma a exclusão dos dados?");
            if (i == 0) {

                try {
                    Empresa.excluir(empresaSelecionada.getId());
                    btnLimparEmpresaActionPerformed(null);
                } catch (EmpresaInvalidaException ex) {
                    Logger.getLogger(TelaEmpresa.class.getName()).log(Level.SEVERE, null, ex);

                } catch (SQLException ex) {
                    Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Erro ao excluir empresa do banco de dados.,");
                }
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private class AcaoPesquisaEmpresa implements ActionListener {

        private JTextField filtro;
        private JComboBox<String> tipoFiltro;
        private DefaultTableModel tabela;
        private List<Empresa> empresas;
        private Empresa empresa;

        public AcaoPesquisaEmpresa(JTextField filtro, JComboBox<String> tipoFiltro, DefaultTableModel tabela) {
            this.filtro = filtro;
            this.tipoFiltro = tipoFiltro;
            this.tabela = tabela;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                if (tipoFiltro.getSelectedIndex() == 2) {

                    String cnpj = filtro.getText();
                    empresa = Empresa.buscarPorCNPJ(cnpj);
                    if (empresa == null) {
                        JOptionPane.showMessageDialog(null, "Empresa não encontrada");
                        this.filtro.setText("");
                        this.filtro.requestFocus();
                        tabela.setRowCount(0);
                    } else {
                        tabela.setRowCount(0);
                        tabela.addRow(
                                new String[]{empresa.getId().toString(), empresa.getNome(), empresa.getCnpj()});
                    }

                } else if (tipoFiltro.getSelectedIndex() == 1) {
                    String nome = filtro.getText();
                    empresas = Empresa.buscarPorNome(nome);
                    if (empresas == null) {
                        JOptionPane.showMessageDialog(null, "Empresa não encontrada");
                        this.filtro.setText("");
                        this.filtro.requestFocus();
                        tabela.setRowCount(0);
                    } else {
                        for (Empresa i : empresas) {
                            tabela.addRow(
                                    new String[]{i.getId().toString(), i.getNome(), i.getCnpj()});
                        }
                    }

                } else if (tipoFiltro.getSelectedIndex() == 0) {
                    Integer id = Integer.parseInt(filtro.getText());
                    empresa = Empresa.buscarPorId(id);
                    if (empresa == null) {
                        JOptionPane.showMessageDialog(null, "Empresa não encontrada");
                        this.filtro.setText("");
                        this.filtro.requestFocus();
                        tabela.setRowCount(0);
                    } else {
                        tabela.setRowCount(0);
                        tabela.addRow(
                                new String[]{empresa.getId().toString(), empresa.getNome(), empresa.getCnpj()});
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(TelaContrato.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private class AcaoSelecionarEmpresa implements ActionListener {

        private JTable tabela;
        private TelaPesquisa tela;

        public AcaoSelecionarEmpresa(JTable tabela, TelaPesquisa tela) {
            this.tabela = tabela;
            this.tela = tela;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            int selecionada = tabela.getSelectedRow();
            if (selecionada == -1) {
                JOptionPane.showMessageDialog(null, "Nenhum registro selecionado");
            } else {
                int id = Integer.parseInt(tabela.getValueAt(selecionada, 0).toString());
                try {
                    empresaSelecionada = Empresa.buscarPorId(id);
                    if (empresaSelecionada == null) {
                        JOptionPane.showMessageDialog(null, "Empresa não encontrada, faça a consulta novamente.");
                    } else {
                        
                        txtCNPJEmpresa.setText(CpfCnpjUtil.formatarCpfCnpj(empresaSelecionada.getCnpj()));
                        txtNomeEmpresa.setText(empresaSelecionada.getNome());
                        tela.setVisible(false);

                    }

                } catch (SQLException ex) {
                    Logger.getLogger(TelaContrato.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Erro! Favor entrar em contato com o Administrador do sistema.");
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmpresa(null, true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarEmpresa;
    private javax.swing.JButton btnLimparEmpresa;
    private javax.swing.JButton btnSalvarEmpresa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblBairroEm;
    private javax.swing.JLabel lblCNPJEm;
    private javax.swing.JLabel lblCidadeEm;
    private javax.swing.JLabel lblEmailEm;
    private javax.swing.JLabel lblEnderecoEm;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObservacoesEm;
    private javax.swing.JLabel lblResponsavelEmpresa;
    private javax.swing.JLabel lblTelEm;
    private javax.swing.JLabel lblUFEm;
    private javax.swing.JTextField txtBairroEmpresa;
    private javax.swing.JTextField txtCNPJEmpresa;
    private javax.swing.JTextField txtCidadeEmpresa;
    private javax.swing.JTextField txtEmailEmpresa;
    private javax.swing.JTextField txtEnderecoEmpresa;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JTextField txtObservacoesEmpresa;
    private javax.swing.JTextField txtResponsavelEmpresa;
    private javax.swing.JTextField txtTelEmpresa;
    private javax.swing.JTextField txtUFEmpresa;
    // End of variables declaration//GEN-END:variables

}
