/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.newtonpaiva.gc.ui.convenio;

import br.newtonpaiva.gc.ui.contrato.TelaContrato;
import br.newtonpaiva.modelo.Convenio;
import br.newtonpaiva.modelo.Curso;
import br.newtonpaiva.modelo.SituacaoConvenio;
import br.newtonpaiva.util.CpfCnpjUtil;
import br.newtonpaiva.util.DateUtil;
import br.newtonpaiva.util.StringUtil;
import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guilherme
 */
public class TodosConvenios extends javax.swing.JDialog {

    private final ResourceBundle bundle = ResourceBundle.getBundle("MessageBundle");

    /**
     * Creates new form TodosConvenios
     *
     * @param parent
     * @param modal
     */
    public TodosConvenios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //posiciona a tela no centro da tela
        setLocationRelativeTo(parent);
        //Atualiza a tabela
        atualizarTabela();
        //Cria as informações para aparacer em cursos
        CursosComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBuscar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        cbbSituacaoConvenio = new javax.swing.JComboBox<>();
        lblSituacaoConvenio = new javax.swing.JLabel();
        cbbCurso = new javax.swing.JComboBox<>();
        lblCurso = new javax.swing.JLabel();
        lblDataEntrada = new javax.swing.JLabel();
        edtVencimentoDe = new javax.swing.JFormattedTextField();
        lblCnpj = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        edtVencimentoAte = new javax.swing.JFormattedTextField();
        lblDataEntradaAte = new javax.swing.JLabel();
        edtAssinaturaAte = new javax.swing.JFormattedTextField();
        lblDataAssinaturaAte = new javax.swing.JLabel();
        edtAssinaturaDe = new javax.swing.JFormattedTextField();
        lblDataAssinaturaAte1 = new javax.swing.JLabel();
        jspCnpj = new javax.swing.JTextField();
        imgLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConvenios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Todos convênios");
        setResizable(false);

        panBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cbbSituacaoConvenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleciona um...", "Andamento", "Cancelado", "Finalizado" }));

        lblSituacaoConvenio.setText("Situação do convênio");

        cbbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleciona um..." }));

        lblCurso.setText("Curso");

        lblDataEntrada.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDataEntrada.setText("Data de vencimento de");

        edtVencimentoDe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        lblCnpj.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCnpj.setText("CNPJ");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        edtVencimentoAte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        lblDataEntradaAte.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDataEntradaAte.setText("Data de vencimento até");

        edtAssinaturaAte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        lblDataAssinaturaAte.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDataAssinaturaAte.setText("Data de assinatura até");

        edtAssinaturaDe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        lblDataAssinaturaAte1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDataAssinaturaAte1.setText("Data de assinatura de");

        jspCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formatarCNPJ(evt);
            }
        });

        javax.swing.GroupLayout panBuscarLayout = new javax.swing.GroupLayout(panBuscar);
        panBuscar.setLayout(panBuscarLayout);
        panBuscarLayout.setHorizontalGroup(
            panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSituacaoConvenio)
                            .addComponent(cbbSituacaoConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCurso)
                            .addComponent(cbbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar))
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataAssinaturaAte1)
                            .addComponent(edtAssinaturaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataAssinaturaAte)
                            .addComponent(edtAssinaturaAte, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataEntrada)
                            .addComponent(edtVencimentoDe, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataEntradaAte)
                            .addComponent(edtVencimentoAte, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panBuscarLayout.createSequentialGroup()
                                .addComponent(lblCnpj)
                                .addGap(97, 97, 97))
                            .addComponent(jspCnpj))))
                .addContainerGap())
        );
        panBuscarLayout.setVerticalGroup(
            panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addComponent(lblSituacaoConvenio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbSituacaoConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addComponent(lblCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addComponent(lblDataEntrada)
                        .addGap(8, 8, 8)
                        .addComponent(edtVencimentoDe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCnpj)
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addComponent(lblDataAssinaturaAte)
                        .addGap(8, 8, 8)
                        .addComponent(edtAssinaturaAte, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addComponent(lblDataAssinaturaAte1)
                        .addGap(8, 8, 8)
                        .addComponent(edtAssinaturaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addComponent(lblDataEntradaAte)
                        .addGap(8, 8, 8)
                        .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtVencimentoAte, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNovo))
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tblConvenios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblConvenios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(panBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(imgLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imgLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(panBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //Atualiza a tabela
        atualizarTabela();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        //Chama a tela de Contrato com o modal
        TelaConvenios Tela = new TelaConvenios(null, true);
        //Tela de Contrato visivel
        Tela.setVisible(true);
        //Atualiza a tabela
        atualizarTabela();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void formatarCNPJ(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatarCNPJ
        // TODO add your handling code here:
        
        String cnpj = CpfCnpjUtil.formatarCpfCnpj(jspCnpj.getText());

        if(StringUtil.isNullOrWhiteSpace(cnpj))
            jspCnpj.setText("");
        else
            jspCnpj.setText(cnpj);
    }//GEN-LAST:event_formatarCNPJ

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TodosConvenios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TodosConvenios dialog = new TodosConvenios(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox<String> cbbCurso;
    private javax.swing.JComboBox<String> cbbSituacaoConvenio;
    private javax.swing.JFormattedTextField edtAssinaturaAte;
    private javax.swing.JFormattedTextField edtAssinaturaDe;
    private javax.swing.JFormattedTextField edtVencimentoAte;
    private javax.swing.JFormattedTextField edtVencimentoDe;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jspCnpj;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDataAssinaturaAte;
    private javax.swing.JLabel lblDataAssinaturaAte1;
    private javax.swing.JLabel lblDataEntrada;
    private javax.swing.JLabel lblDataEntradaAte;
    private javax.swing.JLabel lblSituacaoConvenio;
    private javax.swing.JPanel panBuscar;
    private javax.swing.JTable tblConvenios;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabela() {

        try {

            UrgenciaConvenioTableCellRenderer render = new UrgenciaConvenioTableCellRenderer();

            DefaultTableModel tableModel = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            tableModel.addColumn(bundle.getString("geral.id"));
            tableModel.addColumn(bundle.getString("contratos.grade.empresa"));
            tableModel.addColumn(bundle.getString("geral.curso"));
            tableModel.addColumn(bundle.getString("convenio.geral.situacao"));
            tableModel.addColumn(bundle.getString("convenio.geral.data.assinatura"));
            tableModel.addColumn(bundle.getString("convenio.geral.data.vencimento"));
            tableModel.setRowCount(0);

            Calendar dataAssinaturaDe =  DateUtil.converter(edtAssinaturaDe.getText());
            Calendar dataAssinaturaAte = DateUtil.converter(edtAssinaturaAte.getText());
            Calendar dataVencimentoDe = DateUtil.converter(edtVencimentoDe.getText());
            Calendar dataVencimentoAte = DateUtil.converter(edtVencimentoAte.getText());

            String cnpj = null;

            if (!StringUtil.isNullOrWhiteSpace(jspCnpj.getText())) {
                cnpj = jspCnpj.getText();
            }

            SituacaoConvenio situacao = null;

            if (cbbSituacaoConvenio.getSelectedIndex() > 0) {
                situacao = SituacaoConvenio.values()[cbbSituacaoConvenio.getSelectedIndex() - 1];
            }

            String curso;

            if (cbbCurso.getSelectedIndex() == 0) {
                curso = "";
            } else {
                curso = cbbCurso.getSelectedItem().toString();
            }

            List<Convenio> lista = Convenio.buscarTodos(dataAssinaturaDe, 
                    dataAssinaturaAte, dataVencimentoDe, dataVencimentoAte, cnpj, situacao, curso);

            for (int i = 0; i < lista.size(); i++) {
                Convenio convenio = lista.get(i);
                //Define as cores das linhas
                if (DateUtil.getDifferenceDays(Calendar.getInstance(), convenio.getDataVencimento()) <= 15) {
                    render.critico.add(i);
                } else if (DateUtil.getDifferenceDays(Calendar.getInstance(), convenio.getDataVencimento()) <= 90) {
                    render.alto.add(i);
                } else if (DateUtil.getDifferenceDays(Calendar.getInstance(), convenio.getDataVencimento()) <= 120) {
                    render.medio.add(i);
                }
                //Define as informações da tabela
                SimpleDateFormat f = new SimpleDateFormat(bundle.getString("geral.formato.data"));
                Object[] row = {convenio.getId(), convenio.getEmpresa().getNome(),
                    convenio.getCurso().getCurso(), convenio.getSituacao(),
                    f.format(convenio.getDataAssinatura().getTime()),
                    f.format(convenio.getDataVencimento().getTime())
                };
                tableModel.addRow(row);
            }
            tblConvenios.setDefaultRenderer(Object.class, render);
            tblConvenios.setModel(tableModel);

        } catch (SQLException ex) {
            Logger.getLogger(TodosConvenios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void CursosComponente() {
        try {
            List<Curso> lista = Curso.buscarTodos();
            // Limpa o componente
            cbbCurso.removeAllItems();
            cbbCurso.addItem(bundle.getString("geral.seleciona.um"));
            lista.forEach(emp -> {
                cbbCurso.addItem(emp.getCurso());
            });

        } catch (SQLException ex) {
            Logger.getLogger(TelaContrato.class
                    .getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, bundle.getString("erro.conexao.banco"));
        }
    }

    private class UrgenciaConvenioTableCellRenderer extends DefaultTableCellRenderer {

        public List<Integer> critico = new ArrayList<>();
        public List<Integer> alto = new ArrayList<>();
        public List<Integer> medio = new ArrayList<>();

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int col) {
            final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);

            if (critico.contains(row)) {
                c.setBackground(Color.RED);
            } else if (alto.contains(row)) {
                c.setBackground(Color.CYAN);
            } else if (medio.contains(row)) {
                c.setBackground(Color.YELLOW);
            } else {
                c.setBackground(Color.WHITE);
            }

            return c;
        }
    }
}
