/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.newtonpaiva.gc.ui.usuario;

import br.newtonpaiva.gc.ui.utils.MensagemUtil;
import br.newtonpaiva.modelo.Usuario;
import br.newtonpaiva.modelo.excecoes.UsuarioInvalidoConfirmacaoSenhaNuloException;
import br.newtonpaiva.modelo.excecoes.UsuarioInvalidoSenhaConfirmacaoSenhaNuloException;
import br.newtonpaiva.modelo.excecoes.UsuarioInvalidoSenhaNuloException;
import br.newtonpaiva.modelo.excecoes.UsuarioSenhaAtualInvalidoException;
import br.newtonpaiva.modelo.excecoes.UsuarioSenhaAtualNuloInvalidoException;
import br.newtonpaiva.modelo.excecoes.UsuarioTamanhoSenhaInvalidoException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class TelaAlterarSenha extends javax.swing.JDialog {

    private Usuario usuarioEdicao;

    /**
     * Creates new form TelaAlterarSenha
     * @param parent
     * @param modal
     */
    public TelaAlterarSenha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        /*
        * posiciona a tela no centro da tela
         */
        setLocationRelativeTo(parent);
        /*
        * ao usuário clicar enter ele aciona o botão Salvar
         */
        getRootPane().setDefaultButton(btnSalvar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLogo = new javax.swing.JLabel();
        edtConfSenha = new javax.swing.JPasswordField();
        lblConfSenha = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        edtSenha = new javax.swing.JPasswordField();
        lblSenha1 = new javax.swing.JLabel();
        edtSenhaAtual = new javax.swing.JPasswordField();
        lblNomeUsuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar a senha");
        setResizable(false);

        lblConfSenha.setText("Confirmar senha");

        lblSenha.setText("Senha");

        lblSenha1.setText("Senha Atual");

        lblNomeUsuario.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblNomeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNomeUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(imgLogo))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSenha1)
                                    .addComponent(edtSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSenha)
                                            .addComponent(edtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblConfSenha)
                                            .addComponent(edtConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imgLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblConfSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        //Trabalha com as senhas
        String SenhaAtual = String.valueOf(edtSenhaAtual.getPassword());
        String Senha = String.valueOf(edtSenha.getPassword());
        String ConfSenha = String.valueOf(edtConfSenha.getPassword());
        //Seta a senha digita na classe de usuários
        usuarioEdicao.setSenha(Senha);
        usuarioEdicao.setSenhaConfirmacao(ConfSenha);
        usuarioEdicao.setSenhaAtual(SenhaAtual);
        try {
            //Salva a senha
            if(Senha.equals(ConfSenha)){
                
            usuarioEdicao.salvarSenha();
            //Mensagem de alerta
            MensagemUtil.exibirDialogo("usuario.alteracao.confirmacao.senha");
            //Fecha a teladiferentes
            this.setVisible(false);
            }else{
                MensagemUtil.exibirDialogo("usuario.confirmacao.senha.diferentes");
                edtConfSenha.setText("");
                edtSenha.setText("");
                edtSenhaAtual.setText("");
                edtSenhaAtual.requestFocus();
              }
            
            
        } catch (UsuarioSenhaAtualNuloInvalidoException ex) {
                edtConfSenha.setText("");
                edtSenha.setText("");
                edtSenhaAtual.setText("");
                edtSenhaAtual.requestFocus();
            Logger.getLogger(TelaAlterarSenha.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (UsuarioSenhaAtualInvalidoException ex) {
                edtSenhaAtual.requestFocus();
                edtConfSenha.setText("");
                edtSenha.setText("");
                edtSenhaAtual.setText("");
                Logger.getLogger(TelaAlterarSenha.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (UsuarioInvalidoSenhaNuloException ex) {
                edtConfSenha.setText("");
                edtSenha.setText("");
                edtSenhaAtual.setText("");
                edtSenhaAtual.requestFocus();
            Logger.getLogger(TelaAlterarSenha.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (UsuarioInvalidoConfirmacaoSenhaNuloException ex) {
                edtConfSenha.setText("");
                edtSenha.setText("");
                edtSenhaAtual.setText("");
                edtSenhaAtual.requestFocus();
            Logger.getLogger(TelaAlterarSenha.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (UsuarioTamanhoSenhaInvalidoException ex) {
                edtConfSenha.setText("");
                edtSenha.setText("");
                edtSenhaAtual.setText("");
                edtSenhaAtual.requestFocus();
            Logger.getLogger(TelaAlterarSenha.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (UsuarioInvalidoSenhaConfirmacaoSenhaNuloException ex) {
                edtConfSenha.setText("");
                edtSenha.setText("");
                edtSenhaAtual.setText("");
                edtSenhaAtual.requestFocus();
            Logger.getLogger(TelaAlterarSenha.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (SQLException ex) {
            Logger.getLogger(TelaAlterarSenha.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaAlterarSenha dialog = new TelaAlterarSenha(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    public void exibirDados(Usuario u) {
        /*
        * Informa qual usuário está sendo alterada a senha
         */
        lblNomeUsuario.setText("Alterar a senha do usuário: " + u.getNome());
        //Iguala a classe que veio a variavel global
        usuarioEdicao = u;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPasswordField edtConfSenha;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JPasswordField edtSenhaAtual;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfSenha;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenha1;
    // End of variables declaration//GEN-END:variables
}
